export default function DetailsPanel({ mode, aoi, startDate, endDate, setStartDate, setEndDate, selectedProduct, onSearch, onRun, searching, loading, readiness, analysis }) {
  const result = analysis?.result;
  const candidate = result?.candidate;
  const status = loading ? 'ANALYZING SENTINEL-1 IMAGERY' : candidate === true ? 'POTENTIAL OIL SPILL DETECTED' : candidate === false ? 'NO OIL SPILL CANDIDATE DETECTED' : 'READY FOR ANALYSIS';
  return <aside className="details-column">
    <section className="panel control-panel"><div className="panel-heading"><span>{mode === 'historical' ? 'HISTORICAL ANALYSIS' : 'SENTINEL-1 ACQUISITION MONITORING'}</span><span className="technical-badge">{mode.toUpperCase()}</span></div>
      <p className="control-hint">Navigate the map and drag to draw the AOI used for catalogue search.</p>
      <div className="aoi-readout"><span>SELECTED AOI</span><strong>{aoi ? aoi.map((value) => value.toFixed(3)).join(' / ') : 'NONE'}</strong></div>
      <label>START DATE<input type="date" value={startDate} max={endDate} onChange={(event) => setStartDate(event.target.value)} /></label>
      <label>END DATE<input type="date" value={endDate} min={startDate} onChange={(event) => setEndDate(event.target.value)} /></label>
      <button className="run-button" onClick={onSearch} disabled={searching || !aoi}>{searching ? 'SEARCHING CDSE...' : 'SEARCH SENTINEL-1'}</button>
      <button className="run-button secondary-button" onClick={onRun} disabled={loading || !selectedProduct}>{loading ? 'PROCESSING...' : 'RUN STAGE 1 ANALYSIS'}</button>
      <small className="data-note">{readiness?.providers?.cdse ? 'CDSE credentials configured' : 'CDSE authentication unavailable'}</small>
    </section>
    <section className={`panel result-panel ${candidate === true ? 'candidate-result' : candidate === false ? 'clear-result' : ''}`}><div className="panel-heading"><span>ANALYSIS RESULT</span><span className="technical-badge">{status}</span></div>{result ? <><div className="detail-grid"><div><span>PROBABILITY</span><strong>{Math.round(result.classification_probability * 100)}%</strong></div><div><span>THRESHOLD</span><strong>{Math.round(result.classification_threshold * 100)}%</strong></div><div><span>MODEL</span><strong>{result.model} {result.model_version}</strong></div><div><span>INPUT</span><strong>{result.input_channels.join(' + ')}</strong></div><div><span>ACQUISITION</span><strong>{result.acquisition_time || selectedProduct?.acquisition_time || 'Unavailable'}</strong></div><div><span>PRODUCT ID</span><strong>{result.acquisition_id || selectedProduct?.id || 'Unavailable'}</strong></div><div><span>SOURCE</span><strong>{result.source} / {result.processing?.collection || 'CDSE'}</strong></div><div><span>AOI</span><strong>{aoi ? aoi.map((value) => value.toFixed(2)).join(' / ') : 'Unavailable'}</strong></div></div><div className="sar-previews"><figure><img src={result.previews?.vv} alt="Sentinel-1 VV backscatter" /><figcaption>VV · SOURCE: SENTINEL-1 · PROCESSING: CDSE</figcaption></figure><figure><img src={result.previews?.vh} alt="Sentinel-1 VH backscatter" /><figcaption>VH · SOURCE: SENTINEL-1 · PROCESSING: CDSE</figcaption></figure></div></> : <p className="disclaimer">No analysis result is available. Search and select a real Sentinel-1 acquisition first.</p>}</section>
    <section className="panel future-panel"><div className="panel-heading"><span>NEXT ANALYSIS STAGES</span></div><p>Stage 2 — OpenDrift reconstruction<br /><small>Not yet connected</small></p><p>Stage 3 — AIS correlation<br /><small>Not yet connected</small></p></section>
  </aside>;
}
